server:
  port: 10000

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://10.4.4.208:${server.port}/eureka

spring:
  application:
    name: center